### PR TITLE
[UPDATE] Follow focus

### PR DESCRIPTION
**Pull request by xaiki**
this adds a patch on https://github.com/WayfireWM/wayfire-plugins-extra/pull/17 
it fixes the background will make window loose focus bug, but not the 'alt-tab' one, for that we'd need to intercept that particular focus change and move the mouse, or maybe the alt-tab plugin should do it ?

### CODE REVIEW

**Comment by xaiki** [comment]
FWIW in GNOME if you alt+tab and move mouse, it'll give focus back to the window under the mouse.

**Comment by soreau** [comment]
To pass uncrustify CI check, use [these commands](https://github.com/WayfireWM/wayfire/blob/master/.github/workflows/ci.yaml#L34-L36).

**Comment by soreau** [comment]
but use `--no-backup --replace` instead of --check

**Comment by xaiki** [comment]
```openat(AT_FDCWD, "../wayfire/uncrustify.ini", O_RDONLY) = 3
read(3, "# Uncrustify_d-0.71.0-21-d4da2b0"..., 8191) = 8191
read(3, "   = remove   # ignore/add/remov"..., 8191) = 8191
read(3, "    = force   # ignore/add/remov"..., 8191) = 8191
read(3, "/add/remove/force\n\n# Add or remo"..., 8191) = 8191
read(3, " } <here> b;'. Affects enumerati"..., 8191) = 8191
read(3, "tains an 'else'.\nmod_full_brace_"..., 8191) = 3127
read(3, "", 8191)                       = 0
close(3)                                = 0
fstat(0, {st_mode=S_IFCHR|0620, st_rdev=makedev(0x88, 0x2), ...}) = 0
read(0,
```
uncrustify just hangs on my machine. the CI says it failed because the file changed length that's why i didn't pay attention to it

**Comment by soreau** [comment]
I found a few problems with your code, like starting two timers.. basically I am looking at merging #44. Can you test it and see if everything works like you expect?

**Comment by soreau** [comment]
and if you have additional changes, please separate them into individual patches and make a PR against #44.

**Comment by xaiki** [comment]
i did a review of #44 looking a the code it will focus no-window if moved out.
and i feel it's doing more math than this PR.

I've looked at my code and i don't see how we can get 2 timers:
we start a timer in the callback only if view == last_view, the main branch would exit for exactly the opposite reason.

**Comment by soreau** [comment]
> i did a review of #44 looking a the code it will focus no-window if moved out.
> and i feel it's doing more math than this PR.

It could be doing more math but I think the original call to take the absolute value of the difference between the two points is a better way to do this.

> 
> I've looked at my code and i don't see how we can get 2 timers:
> we start a timer in the callback only if view == last_view, the main branch would exit for exactly the opposite reason.

For one, I don't really like the idea of setting up the timer from its callback. This should only be done from the motion handler. Another is that there is some bug I can't put my finger on, where the view focuses and then raises after the timeout, which causes an unfavorable visual glitch. Also, it would seem that your code can get in an infinite loop of timers while the mouse is sitting still. Just put a debug print statement at the top of `view_changed_cb` and set the minimum cursor movement option to maybe 100, then move the cursor into another window but not more than 100.. it will be in an infinite loop, setting timers constantly.

**Comment by xaiki** [comment]
by raise you mean goes to the foreground ? i can't reproduce. what is happening here is that efectively the widget toolkit will repaint the windows on focus gain/loss causing visual feedback, and it's what you want: know that your focus has switched.

it's the way it's supposed to work, if you move your mouse less than threshold we'll check periodically if you got to that threshold. I guess i could add a new variable like 'waiting_for_threhshold' and make pointer_motion into a state machine... but it'd get all a little more complicated. that would also avoid the timer in callback.

**Comment by soreau** [comment]
> by raise you mean goes to the foreground ? i can't reproduce. what is happening here is that efectively the widget toolkit will repaint the windows on focus gain/loss causing visual feedback, and it's what you want: know that your focus has switched.

This only happens with your PR. Maybe it has something to do with the loops. It seems to be most easily reproducible with default settings when first starting wayfire.

> 
> it's the way it's supposed to work, if you move your mouse less than threshold we'll check periodically if you got to that threshold. I did that because it'd put the higher load to the most uncommon case: where you put your mouse on another window but didn't cross the threshold. in the other case we'd evaluate everytime the mouse moves, or i'd need to some how debounce the callback in the case that i'm waiting on the user to move it's mouse.

If you mean you are deliberately looping constantly in some kind of polling fashion based on the focus delay timeout, I won't accept a PR that does this.

> 
> I guess i could add a new variable like 'waiting_for_threhshold' and make pointer_motion into a state machine... but it'd get all a little more complicated. that would also avoid the timer in callback.

I would like to keep the original `distance` logic and compare with abs(coords - last_coords).

If you would like to continue working on this, you should submit a PR with a patch for each improvement to #44 (follow-focus branch of this repository).

**Pull request closed without merging**
