### PR TITLE
Add view shot plugin

### PR DESCRIPTION
**Pull request by soreau**
This plugin allows taking screenshots of views.

Requires [this wayfire patch](https://github.com/WayfireWM/wayfire/pull/1146).

### CODE REVIEW

**Comment by ammen99** [comment]
> Requires [this wayfire patch](http://ix.io/2W9i).

I'd rather let plugins have access to the offscreen buffer (something like `const wf::framebuffer_t& view_interface_t::get_snapshot()`)

**Comment by soreau** [comment]
> > Requires [this wayfire patch](http://ix.io/2W9i).
> 
> I'd rather let plugins have access to the offscreen buffer (something like `const wf::framebuffer_t& view_interface_t::get_snapshot()`)

Yea I had thought something similar at first but ended up with what it is currently. However if this is something you would accept into wayfire, I could clean it up.

**Comment by ammen99** [comment]
> Yea I had thought something similar at first but ended up with what it is currently. However if this is something you would accept into wayfire, I could clean it up.

get_snapshot is something I thought would be a good idea for wayfire anyway, we just haven't had a use-case for it up to now :)

**Comment by soreau** [comment]
@ammen99 I have refreshed the wayfire patch and this PR patch, can you check again?

**Pull request merged**
